### ISSUE TITLE
ng serve not working but ng build and serving dist folder works

### ISSUE THREAD

**Issue by MrGoogol** [cebor/angular-highcharts-demo#2]
edit: getting "chartModule is not a function"

**Comment by svkmsr6** [comment]
Can you explain the scenario where this is happening? I mean the steps for reproducing this issue...

**Comment by MrGoogol** [comment]
Approaching 4AM quickly but I was able to learn that ng build and manually serving the dist folder works. It will make it difficult to debug so wondering if anyone has answer to running "ng serve" when unconventionally to angular importing "import { ChartModule, HIGHCHARTS_MODULES } from 'angular-highcharts';" and "import stock from 'highcharts/modules/stock.src';".

That is my guess to why the chartModule is not found when using ng serve. I tested aot flag but that did not help. not sure why compiling with build works?!

**Comment by cebor** [comment]
Known Issue. See: https://github.com/cebor/angular-highcharts/issues/112#issuecomment-355059670 for workaround.
